### ISSUE TITLE
Crash with divide by zero in literals

### ISSUE THREAD

**Issue by tari** [alberthdev/spasm-ng#11]
SIGFPE at parser.cpp:567 when division by zero occurs in a symbol computation. This should be handled gracefully.

Test case:
```z80
.db 0/0
```

**Comment by tari** [comment]
Similar bug with modulo operations at parser.cpp:568.

```
.db 0%0
```

**Comment by adriweb** [comment]
Division by 0 SIGFPE as well  with `#if 0/0` (or `#if0/0`, the space isn't even needed) :

```
Program received signal SIGFPE, Arithmetic exception.
0x0000000000436801 in parse_num_full (expr=0x666f33 "", expr@entry=0x666f30 "0/0", 
    value=value@entry=0x7fffffffdaa0, depth=depth@entry=0) at parser.cpp:567
567				case M_DIV: total /= last_num; break;
(gdb) bt
#0  0x0000000000436801 in parse_num_full (expr=0x666f33 "", expr@entry=0x666f30 "0/0", 
    value=value@entry=0x7fffffffdaa0, depth=depth@entry=0) at parser.cpp:567
#1  0x0000000000436e5b in parse_num (expr=expr@entry=0x666f30 "0/0", 
    value=value@entry=0x7fffffffdaa0) at parser.cpp:120
#2  0x0000000000422f3f in handle_preop_if (ptr=<optimized out>) at preop.cpp:631

```

**Comment by adriweb** [comment]
afl-fuzz + afl-tmin also found these derivatives, FYI:
* `ld l,0%0`
* `cp%%0`
* `.dW0%0`
* `.org0/0`
* `rst$%0`
* `call%%0`
* `ld(0%0),a`
* `.db0/GetC`

All as one-line file input.
