### ISSUE TITLE
Segfault at utils.cpp:121

### ISSUE THREAD

**Issue by tari** [alberthdev/spasm-ng#12]
Test case:
```z80
b(
```

**Comment by tari** [comment]
Stack trace:
```
#0  skip_whitespace (ptr=0x6800007ffff70028 <error: Cannot access memory at address 0x6800007ffff70028>)
    at utils.cpp:121
#1  read_expr_impl (ptr=0x659ec1, word=0x7fffffffd460 "", delims=0x43d14a ")") at utils.cpp:401
#2  0x00000000004067d1 in handle_opcode_or_macro (ptr=0x659ec1 "(") at pass_one.cpp:336
#3  0x000000000040563b in run_first_pass_line (ptr=<optimized out>) at pass_one.cpp:170
#4  run_first_pass (ptr=<optimized out>) at pass_one.cpp:141
#5  0x0000000000402954 in run_assembly () at main.cpp:117
#6  0x000000000040437f in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:431
```
